#!/usr/bin/env python3
"""\
Grab images with chunk data attached and process the appended chunks.

Basler cameras can generate per-image information such as frame counters,
timestamps, and CRC checksums that is appended to the image data as data
"chunks". This sample shows how to enable chunk features, grab images, and
process the appended data.

When the camera is in chunk mode it transfers data blocks that are
partitioned into chunks. The first chunk is always the image data. When
chunk features are enabled, the image data chunk is followed by chunks
containing the information generated by the chunk features.
"""
import sys
from pypylon import pylon


class SampleImageEventHandler(pylon.ImageEventHandler):
    """Read the timestamp chunk from every grabbed image."""

    def OnImageGrabbed(self, camera, grab_result):
        if grab_result.GrabSucceeded():
            # Generic parameter access:
            # This shows the access via the chunk data node map. This method
            # is available for all grab result types.
            chunk_timestamp = pylon.IntegerParameter(
                grab_result.ChunkDataNodeMap, "ChunkTimestamp"
            )
            if chunk_timestamp.IsReadable():
                print(
                    "OnImageGrabbed: TimeStamp (Result) accessed via node map:",
                    chunk_timestamp.Value,
                )

            # Native parameter access:
            # When using the device-specific grab results the chunk data can
            # be accessed via the members of the grab result.
            if grab_result.ChunkTimestamp.IsReadable():
                print(
                    "OnImageGrabbed: TimeStamp (Result) accessed via result member:",
                    grab_result.ChunkTimestamp.Value,
                )


COUNT_OF_IMAGES_TO_GRAB = 5
RETRIEVE_TIMEOUT_MS = 5000

exit_code = 0
try:
    with pylon.InstantCamera(pylon.FirstFound) as camera:
        print("Using device:", camera.DeviceInfo.ModelName)

        camera.RegisterImageEventHandler(
            SampleImageEventHandler(),
            pylon.RegistrationMode_Append,
            pylon.Cleanup_Delete,
        )

        # A GenICam node map is required for accessing chunk data, so a small
        # node map is created for each grab result. Creating a node map can
        # be time-consuming because node maps are built by parsing an XML
        # description file. Node maps are normally created dynamically in
        # StartGrabbing(); to avoid that delay, a static pool of node maps
        # can be created once up front.
        camera.StaticChunkNodeMapPoolSize.TrySetValue(camera.MaxNumBuffer.Value)

        if not camera.ChunkModeActive.TrySetValue(True):
            raise pylon.RuntimeException(
                "The camera doesn't support chunk features."
            )

        available_chunks = []
        if camera.ChunkSelector.IsReadable():
            available_chunks = camera.ChunkSelector.GetSettableValues()

        # Enable timestamp chunks.
        if "Timestamp" in available_chunks:
            if camera.ChunkSelector.TrySetValue("Timestamp"):
                camera.ChunkEnable.TrySetValue(True)

        # USB camera devices provide generic counters. An explicit
        # FrameCounter value is not provided by USB camera devices.
        if "Framecounter" in available_chunks:
            if camera.ChunkSelector.TrySetValue("Framecounter"):
                camera.ChunkEnable.TrySetValue(True)

        # Enable CRC checksum chunks.
        if "PayloadCRC16" in available_chunks:
            if camera.ChunkSelector.TrySetValue("PayloadCRC16"):
                camera.ChunkEnable.TrySetValue(True)

        try:
            # Start the grabbing of COUNT_OF_IMAGES_TO_GRAB images.
            # The camera device is parameterized with a default configuration
            # that sets up free-running continuous acquisition.
            camera.StartGrabbingMax(COUNT_OF_IMAGES_TO_GRAB)

            # StopGrabbing() is called automatically by RetrieveResult() when
            # COUNT_OF_IMAGES_TO_GRAB images have been retrieved.
            while camera.IsGrabbing():
                # RetrieveResult calls the image event handler's
                # OnImageGrabbed method.
                with camera.RetrieveResult(
                    RETRIEVE_TIMEOUT_MS, pylon.TimeoutHandling_ThrowException
                ) as grab_result:
                    if grab_result.GrabSucceeded():
                        # The result data is automatically filled with the
                        # received chunk data. (Note: this is not the case
                        # when using the low-level API.)
                        print("SizeX:", grab_result.Width)
                        print("SizeY:", grab_result.Height)
                        image = grab_result.Array
                        print("Gray value of first pixel:", image[0, 0])

                        # Check that a buffer containing chunk data has been
                        # received.
                        if grab_result.PayloadType != pylon.PayloadType_ChunkData:
                            raise pylon.RuntimeException(
                                "Unexpected payload type received."
                            )

                        # Since the CRC Checksum feature was activated, the
                        # integrity of the buffer can be checked. Enabling
                        # CRC is not a prerequisite for using chunks.
                        if grab_result.HasCRC() and not grab_result.CheckCRC():
                            raise pylon.RuntimeException("Image was damaged!")

                        # Access the chunk data attached to the result.
                        # Check that the chunk is readable; when it is, the
                        # buffer contains the requested chunk data.
                        if grab_result.ChunkTimestamp.IsReadable():
                            print(
                                "Timestamp (Result):",
                                grab_result.ChunkTimestamp.Value,
                            )

                        if (
                            not camera.IsUsb()
                            and grab_result.ChunkFramecounter.IsReadable()
                        ):
                            print(
                                "FrameCounter (Result):",
                                grab_result.ChunkFramecounter.Value,
                            )
                    else:
                        print(
                            "Error:",
                            f"{grab_result.ErrorCode:#x}",
                            grab_result.ErrorDescription,
                        )
                print()
        except pylon.LogicalErrorException:
            # Expected when the camera has limited chunk-mode capabilities.
            print(
                "Logical error: grabbing with chunks is not supported by "
                "this device."
            )
        finally:
            # Disable chunk mode so the camera returns to its default state.
            camera.ChunkModeActive.TrySetValue(False)

except Exception as e:
    print("An exception occurred:", e)
    import traceback
    traceback.print_exc()
    exit_code = 1

sys.exit(exit_code)
