#!/usr/bin/env python3
"""\
 Basler cameras provide chunk features: The cameras can generate certain
 information about each image, e.g. frame counters, time stamps, and CRC
 checksums, that is appended to the image data as data "chunks".
 This sample illustrates how to enable chunk features, how to grab images,
 and how to process the appended data. When the camera is in chunk mode, it
 transfers data blocks that are partitioned into chunks. The first chunk is
 always the image data. When chunk features are enabled, the image data chunk
 is followed by chunks containing the information generated by the chunk
 features.
"""

import sys
from pypylon import pylon





# Example of a device specific handler for image events.
class SampleImageEventHandler(pylon.ImageEventHandler):
    def OnImageGrabbed(self, camera, grabResult):
        # The chunk data is attached to the grab result and can be accessed
        # anywhere, e.g. inside an image event handler.
        time_stamp = grabResult.ChunkTimestamp.GetValueOrDefault(0)
        if time_stamp > 0:
            print(
                "OnImageGrabbed: TimeStamp (Result) accessed via result member:",
                time_stamp,
            )


# Number of images to be grabbed.
COUNT_OF_IMAGES_TO_GRAB = 5

# The exit code of the sample application.
exit_code = 0


# Create an instant camera object with the first found camera device.
with pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice()) as camera:

    # Print the model name of the camera.
    print("Using device ", camera.DeviceInfo.GetFriendlyName())

    # Register an image event handler that accesses the chunk data.
    camera.RegisterImageEventHandler(
        SampleImageEventHandler(),
        pylon.RegistrationMode_Append,
        pylon.Cleanup_Delete,
    )

    # Open the camera.
    camera.Open()

    # A GenICam node map is required for accessing chunk data. That's why a
    # small node map is required for each grab result. Creating a node map can
    # be time-consuming, because node maps are created by parsing an XML
    # description file. The node maps are usually created dynamically when
    # StartGrabbing() is called. To avoid a delay caused by node map creation
    # in StartGrabbing() you have the option to create a static pool of node
    # maps once before grabbing.
    camera.StaticChunkNodeMapPoolSize.TrySetValue(camera.MaxNumBuffer.Value)

    # Enable chunks in general.
    if not camera.ChunkModeActive.TrySetValue(True):
        print( "Unable to activate Chunk Mode" )
    available_chunks = []
    if camera.ChunkSelector.IsReadable():
        available_chunks = camera.ChunkSelector.GetSettableValues()


    # Enable time stamp chunks.
    if "Timestamp" in available_chunks:
        if camera.ChunkSelector.TrySetValue("Timestamp"):
            camera.ChunkEnable.TrySetValue(True)

    # USB camera devices provide generic counters. An explicit FrameCounter
    # value is not provided by USB camera devices.
    if "Framecounter" in available_chunks:
        if camera.ChunkSelector.TrySetValue("Framecounter"):
            camera.ChunkEnable.TrySetValue(True)

    # Enable CRC checksum chunks.
    if "PayloadCRC16" in available_chunks:
        if camera.ChunkSelector.TrySetValue("PayloadCRC16"):
            camera.ChunkEnable.TrySetValue(True)
    try:
        # Start grabbing countOfImagesToGrab images.
        # The camera device is parameterized with a default configuration which
        # sets up free-running continuous acquisition.
        camera.StartGrabbingMax(COUNT_OF_IMAGES_TO_GRAB)

        # Camera.StopGrabbing() is called automatically by the RetrieveResult()
        # method when countOfImagesToGrab images have been retrieved.
        while camera.IsGrabbing():
            # Wait for an image and then retrieve it. A timeout of 5000 ms is used.
            # RetrieveResult calls the image event handler's OnImageGrabbed method.
            with camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException) as grab_result:

                if grab_result.GrabSucceeded():
                    # The result data is automatically filled with received chunk data.
                    # (Note: This is not the case when using the low-level API.)
                    print("SizeX: ", grab_result.Width)
                    print("SizeY: ", grab_result.Height)
                    image = grab_result.Array
                    print("Gray value of first pixel: ", image[0, 0])

                    # Check to see if a buffer containing chunk data has been received.
                    if grab_result.PayloadType != pylon.PayloadType_ChunkData:
                        raise pylon.RuntimeException("Unexpected payload type received.")

                    # Since we have activated the CRC Checksum feature, we can check
                    # the integrity of the buffer first.
                    # Note: Enabling the CRC Checksum feature is not a prerequisite for
                    # using chunks. Chunks can also be handled when the CRC Checksum
                    # feature is deactivated.
                    if grab_result.HasCRC() and not grab_result.CheckCRC():
                        raise pylon.RuntimeException("Image was damaged!")

                    # Access the chunk data attached to the result.
                    # Before accessing the chunk data, you should check to see if the
                    # chunk is readable. When it is readable, the buffer contains the
                    # requested chunk data.
                    if grab_result.ChunkTimestamp.IsReadable():
                        print("TimeStamp (Result): ", grab_result.ChunkTimestamp.Value)

                    # USB camera devices provide generic counters. An explicit FrameCounter value is not provided by USB camera devices.
                    if not camera.IsUsb() and grab_result.ChunkFramecounter.IsReadable():
                        print("FrameCounter (Result): ", grab_result.ChunkFramecounter.Value)

                else:
                    print("Error: ", grab_result.ErrorCode, grab_result.ErrorDescription)
            print()
    except pylon.LogicalErrorException as e:
        # This exception is expected when the camera has limited chunk mode abilities.
        print("Logical error occurred (because grabbing with chunks is not yet implemented).")
    except pylon.GenericException as e:
        # This exception is not expected.
        print("An exception occurred while grabbing:", e)
        import traceback
        traceback.print_exc()
        exit_code = 1
    finally:
        # Disable chunk mode.
        camera.ChunkModeActive.TrySetValue(False)

sys.exit(exit_code)
